unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CPF__c</fullName>
        <label>CPF</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Conta__c</fullName>
        <displayFormat>CT{00000}</displayFormat>
        <label>Conta</label>
        <type>AutoNumber</type>
    </fields>
    <recordTypes>
        <fullName>Jogador</fullName>
        <active>true</active>
        <label>Jogador</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Jogador</fullName>
        <active>true</active>
        <label>Jogador</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/JogadorMesa__c.object
<CustomObject>
    <fields>
        <fullName>DataAtivacao__c</fullName>
        <label>Data Ativação</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jogador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
                <value>
                    <fullName>Em Espera</fullName>
                    <default>true</default>
                    <label>Em Espera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jogador Mesa</label>
    <nameField>
        <displayFormat>JM-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>Jogo__c</fullName>
        <label>Jogo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mix Texas/Omaha</fullName>
                </value>
                <value>
                    <fullName>Omaha</fullName>
                </value>
                <value>
                    <fullName>Texas Holdem</fullName>
                    <default>true</default>
                    <label>Texas Holdem</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo__c</fullName>
        <defaultValue>&quot;Nova Mesa&quot;</defaultValue>
        <description>Titulo pelo o qual a mesa é reconhecida por todos</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCash__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sess_es_Cash</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCaixa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sessao_Jogador</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Jogador</label>
    <nameField>
        <displayFormat>SJ-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Jogador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/JogadorController.cls
public with sharing class JogadorController extends AbstractCashController {

    public List<Contact> jogadorList 				{ get;set; }
    public List<SessaoCash__c> jogadorSessaoList 	{ get;set; }
    
    public List<JogadorMesa__c> jogadorMesaList 	{ get;set; }
    public List<Mesa__c> mesaList 					{ get;set; }
    
    public JogadorController() {}
    
    protected override void init() {
        this.jogadorMesaList 	= new List<JogadorMesa__c>();
        this.jogadorSessaoList 	= new List<SessaoCash__c>();
		this.jogadorList 		= new List<Contact>();
        this.mesaList			= new List<Mesa__c>();
        
        if(sessaoCaixa != null) {
            jogadorSessaoList = [
                SELECT Id, Cliente__r.Id, Cliente__r.FirstName, Cliente__r.LastName,
                CreatedDate, Status__c, Name
                
                FROM SessaoCash__c
                WHERE Status__c = 'Aberta' AND SessaoCaixa__c =: sessaoCaixa.Id
                ORDER BY CreatedDate DESC LIMIT 100
            ];
        
            jogadorMesaList = [
                SELECT Id, Jogador__r.Id, Jogador__r.FirstName, Jogador__r.LastName,
                DataAtivacao__c, Mesa__r.Name, Mesa__r.Titulo__c, Mesa__r.Jogo__c, 
                CreatedBy.Name, CreatedDate, Status__c
                FROM JogadorMesa__c
                WHERE Status__c = 'Ativo' AND Mesa__r.SessaoCaixa__c =: sessaoCaixa.Id
                ORDER BY DataAtivacao__c DESC LIMIT 100
            ];
            
            mesaList = [
                SELECT Id, Name, Jogo__c, Titulo__c, 
                CreatedBy.Name, CreatedDate, Status__c
                FROM Mesa__c
                WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Aberta'
                ORDER BY CreatedDate DESC
            ];
            
        }
    }
    
    public override PageReference buscar() {
        
        if(String.isEmpty(textoChave)) {
            return null;
        }
        
        textoChave = textoChave.trim();
        
        jogadorList = Database.query(
            'SELECT Id, FirstName, LastName, MobilePhone, Email, Account.CPF__c, Account.Conta__c ' 	+ 
            'FROM Contact ' + 
            'WHERE RecordTypeId = \'' + UtilApex.getRecordTypeId('Contact', 'Jogador') + '\'' 				+
            //'WHERE AccountId != null AND Account.RecordTypeId = \'' + UtilApex.getRecordTypeId('Account', 'Jogador') + '\'' 				+
            (String.isNotBlank( textoChave ) ? ' AND (FirstName LIKE \'%' + textoChave + 
             '%\' OR LastName LIKE \'%' 		+ textoChave + 
             '%\' OR Email LIKE \'%' 			+ textoChave +
             //'%\' OR Account.Conta__c LIKE \'%' + textoChave + 
             '%\')' : '') +
            ' ORDER BY LastName ASC LIMIT 100'
        );
        
        return null;
    }
}