unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Conta__c</fullName>
        <displayFormat>CT{00000}</displayFormat>
        <label>Conta</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/DealerSessao__c.object
<CustomObject>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessao Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Dealer</relationshipLabel>
        <relationshipName>Dealers_Sessao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Dealer</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Dealer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>Jogo__c</fullName>
        <label>Jogo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mix Texas/Omaha</fullName>
                </value>
                <value>
                    <fullName>Omaha</fullName>
                </value>
                <value>
                    <fullName>Texas Holdem</fullName>
                    <default>true</default>
                    <label>Texas Holdem</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo__c</fullName>
        <defaultValue>&quot;Nova Mesa&quot;</defaultValue>
        <description>Titulo pelo o qual a mesa é reconhecida por todos</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCash__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sess_es_Cash</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCaixa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sessao_Jogador</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Jogador</label>
    <nameField>
        <displayFormat>SJ-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Jogador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CaixaController.cls
public with sharing class CaixaController extends AbstractCashController {
    
    public List<SessaoCash__c> sessaoList 			{ get;set; }
    public List<DealerSessao__c> dealerSessaoList 	{ get;set; }
    public List<SessaoCash__c> jogSessaoList 		{ get;set; }
    public List<Mesa__c> mesaList 					{ get;set; }
    public CaixaController() { }
    
    public override void init() {
        System.debug('Init()');
        
        this.sessaoList 		= new List<SessaoCash__c>();
        this.dealerSessaoList 	= new List<DealerSessao__c>();
        this.jogSessaoList 		= new List<SessaoCash__c>();
        this.mesaList			= new List<Mesa__c>();
        
        if(sessaoCaixa == null) {
            return;  
        }
        
        dealerSessaoList = ClubeServico.getServico().obterSessoesDealerAberta(sessaoCaixa);
        
        System.debug('dealerSessaoList: ' + dealerSessaoList);
        
        jogSessaoList = [
            SELECT Id, Name, 
            Cliente__c, Cliente__r.FirstName, Cliente__r.LastName, Cliente__r.Account.Conta__c,
            CreatedBy.Name, CreatedDate, Status__c
            
            FROM SessaoCash__c
            WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Aberta'
            ORDER BY CreatedDate DESC LIMIT 20
        ];
        
        System.debug('jogSessaoList: ' + jogSessaoList);
        
        mesaList = [
            SELECT Id, Name, Jogo__c, Titulo__c, 
            CreatedBy.Name, CreatedDate, Status__c
            FROM Mesa__c
            WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Aberta'
            ORDER BY CreatedDate DESC
        ];
    }
    
    public override PageReference buscar() {
        
        if(String.isEmpty(textoChave) || sessaoCaixa == null) {
            return null;
        }
        
        textoChave = textoChave.trim();
        
        Id sId = sessaoCaixa.Id;
        
        sessaoList = Database.query(
            'SELECT Id, Name, Cliente__c, Cliente__r.FirstName, Cliente__r.LastName, Cliente__r.Account.Conta__c,'
            + 'CreatedBy.Name, CreatedDate, Status__c ' 	+ 
            'FROM SessaoCash__c ' 			+ 
            'WHERE Status__c = \'Aberta\' ' +
            (String.isNotBlank( textoChave ) ? 'AND (Cliente__r.FirstName LIKE \'%' + textoChave + 
             '%\' OR Cliente__r.LastName LIKE \'%' 		+ textoChave +  
             '%\' OR Cliente__r.Account.Conta__c LIKE \'%' + textoChave + 
             '%\')' : '') + ' AND SessaoCaixa__c =: sId ' + 
            ' ORDER BY Cliente__r.FirstName ASC LIMIT 100'
        );
        
        return null;
    }
}