unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CPF__c</fullName>
        <label>CPF</label>
        <length>11</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Dealer</fullName>
        <active>true</active>
        <label>Dealer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/DealerMesa__c.object
<CustomObject>
    <fields>
        <fullName>DataSaida__c</fullName>
        <label>Data Saída</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DealerSessao__c</fullName>
        <label>Dealer Sessão</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DealerSessao__c.Status__c</field>
                <operation>equals</operation>
                <value>Ativo</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DealerSessao__c</referenceTo>
        <relationshipLabel>Dealers Mesas</relationshipLabel>
        <relationshipName>Dealers_Mesas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Dealers Mesas</relationshipLabel>
        <relationshipName>Dealers_Mesas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ValorCapile__c</fullName>
        <label>Valor Capilé</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dealer Mesa</label>
    <nameField>
        <displayFormat>DM-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/DealerSessao__c.object
<CustomObject>
    <fields>
        <fullName>DataSaida__c</fullName>
        <label>Data Saida</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Dealer</relationshipLabel>
        <relationshipName>Dealers_Sessao</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessao Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Dealer</relationshipLabel>
        <relationshipName>Dealers_Sessao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Dealer</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Dealer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/DealerController.cls
public with sharing class DealerController extends AbstractCashController {

    public List<DealerSessao__c> dealerSessaoList { get;set; }
    
    public List<Contact> dealerList 	{ get;set; }
    public DealerSessao__c dSessao		{ get;set; }
    
    public DealerMesa__c dMesa 	{ get;set; }
    public Contact dealer 		{ get;set; }
    
    public DealerController() { }
    
    protected override void init() {        
        this.dealerSessaoList = new List<DealerSessao__c>();
        
        if(sessaoCaixa == null) {
            return;
        }
        
        dealerSessaoList = ClubeServico.getServico().obterSessoesDealerAberta(sessaoCaixa);
        
        String dId = Apexpages.currentPage().getParameters().get('Id');
        if(!String.isEmpty(dId)) { //adicionar dealer na mesa
            
            List<Contact> dealerList = [SELECT Id, LastName, FirstName FROM Contact WHERE Id =: dId];
            if(dealerList.isEmpty()) {
                return;
            } else {
                dealer = dealerList.get(0);
                
            }
            
            List<DealerSessao__c> dSessaoList = [
                SELECT Id, Dealer__c, Dealer__r.FirstName, Dealer__r.LastName
                FROM DealerSessao__c
                
                WHERE Dealer__c=: dId AND Dealer__r.RecordTypeId =: UtilApex.getRecordTypeId('Contact', 'Dealer') 
                AND SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Ativo'
            ];
            
            if(dSessaoList.isEmpty()) {
                ApexPages.addMessage(new ApexPages.Message(
                    ApexPages.Severity.WARNING, 'O dealer não está ativo para registro em mesa'));
                //throw new UtilApex.UtilApexException('Sessão Dealer não encontrado');
                return;
            }
            
            dSessao = dSessaoList.get(0);
            
            dMesa = new DealerMesa__c();
            dMesa.DealerSessao__c = dSessao.Id;
            dMesa.Dealer__c = dSessao.Dealer__c;
            dMesa.ValorCapile__c = 0;
            dMesa.DataSaida__c = Datetime.now();
        }
    }
    
    public override PageReference buscar() {
        
        if(!String.isEmpty(textoChave)) {
            textoChave = textoChave.trim();
        }
        
        dealerList = Database.query(
            'SELECT Id, FirstName, LastName, MobilePhone, Email, Account.CPF__c ' 	+ 
            'FROM Contact ' 					+ 
            'WHERE RecordTypeId = \'' + UtilApex.getRecordTypeId('Contact', 'Dealer') + '\'' 	+
            (String.isNotBlank( textoChave ) ? 'AND (FirstName LIKE \'%' + textoChave + 
             '%\' OR LastName LIKE \'%' 		+ textoChave + 
             '%\' OR Email LIKE \'%' 			+ textoChave +
             '%\')' : '') +
            ' ORDER BY LastName ASC LIMIT 100'
        );
        
        return null;   
    }
    
    public PageReference addDealerMesa() {
        
        try {
            System.debug('Dealer Mesa: ' + dMesa);
            
            INSERT dMesa;
            
            //ClubeServico.getServico().atualizarSessaoDealer(dSessao);
            
        } catch(Exception ex) {
            System.debug('Ex: ' + ex);
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Ex: ' + ex.getMessage()));
            
            return null;
        }
        
        return cancelar();
    }
    
    protected override String getUrl() {
        String chave = obterChaveContato(dealer);
        return '/apex/Dealer?sfdc.tabName=01r61000000hot0&chave=' + chave;
    }
}