unpackaged/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Jogador</fullName>
        <active>true</active>
        <label>Jogador</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/CompraFicha__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Compras Fichas</relationshipLabel>
        <relationshipName>Compras_Fichas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fichas__c</fullName>
        <label>Fichas</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FormaPagamento__c</fullName>
        <label>Forma Pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                    <default>true</default>
                    <label>Dinheiro</label>
                </value>
                <value>
                    <fullName>Cartão/Débito</fullName>
                </value>
                <value>
                    <fullName>Cartão/Crédito</fullName>
                </value>
                <value>
                    <fullName>Vale/Crédito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mesa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Compras Fichas</relationshipLabel>
        <relationshipName>Compras_Fichas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SessaoCash__c</fullName>
        <label>Sessao Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCash__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCash__c</referenceTo>
        <relationshipLabel>Compras Fichas</relationshipLabel>
        <relationshipName>Compras_Fichas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                </value>
                <value>
                    <fullName>Paga</fullName>
                    <default>true</default>
                    <label>Paga</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valor_Total__c</fullName>
        <label>Valor Total</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Compra Ficha</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compras Fichas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Jogador</fullName>
        <active>true</active>
        <label>Jogador</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCash__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sess_es_Cash</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CobrarTaxa__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Cobrar Taxa de Pagamento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FichaDevolvida__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Total Fichas Devolvidas</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FormaPagamento__c</fullName>
        <label>Forma de Pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão/Débito</fullName>
                </value>
                <value>
                    <fullName>Cartão/Crédito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCaixa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sessao_Jogador</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalFichasPendente__c</fullName>
        <label>Total Fichas Pendentes</label>
        <summarizedField>CompraFicha__c.Fichas__c</summarizedField>
        <summaryFilterItems>
            <field>CompraFicha__c.Status__c</field>
            <operation>equals</operation>
            <value>Aberta</value>
        </summaryFilterItems>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFichas__c</fullName>
        <label>Total Fichas</label>
        <summarizedField>CompraFicha__c.Fichas__c</summarizedField>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>UsuarioFechamento__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Referencia ao usuário que efetuou a Ação de fechamento da sessão do jogador</description>
        <inlineHelpText>Referencia ao usuário que efetuou a Ação de fechamento da sessão do jogador</inlineHelpText>
        <label>Usuário Fechamento</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sessoes_Jogador</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ValorCompra__c</fullName>
        <label>Valor da Compra</label>
        <summarizedField>CompraFicha__c.Valor_Total__c</summarizedField>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorTotalPago__c</fullName>
        <label>Valor Total Pago (+)</label>
        <summarizedField>CompraFicha__c.Valor_Total__c</summarizedField>
        <summaryFilterItems>
            <field>CompraFicha__c.Status__c</field>
            <operation>equals</operation>
            <value>Paga</value>
        </summaryFilterItems>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorTotalPendente__c</fullName>
        <label>Valor Total Pendente (-)</label>
        <summarizedField>CompraFicha__c.Valor_Total__c</summarizedField>
        <summaryFilterItems>
            <field>CompraFicha__c.Status__c</field>
            <operation>equals</operation>
            <value>Aberta</value>
        </summaryFilterItems>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorTotal__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Total (=)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Sessão Jogador</label>
    <nameField>
        <displayFormat>SJ-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Jogador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/SessaoJogadorController.cls
public with sharing class SessaoJogadorController extends AbstractCashController {
    
    public String sessaoJogadorId 		{ get;set; }
    public SessaoCash__c sessaoJogador 	{ get;set; }
    
    public List<CompraFicha__c> compraList	{ get;set; }
    
    public Contact jogador 					{ get;set; }
    public Account accClube					{ get;set; }
    public Boolean btnAtivo					{ get;set; }
    
    public SessaoJogadorController() { 
    	sessaoJogadorId = Apexpages.currentPage().getParameters().get('Id'); 
    }
    
    protected override void init() {    
        
        if(sessaoCaixa == null) {
            return;
        }
        
        String sessaoId = Apexpages.currentPage().getParameters().get('Id'); 
        
        if(!atualizarValorSessao(sessaoId)) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Não foi possível encontrar a sessão do cliente'));
            return;
        }
       
        jogador = new Contact(Id=sessaoJogador.Cliente__c);
        jogador.LastName = sessaoJogador.Cliente__r.LastName;
        jogador.FirstName = sessaoJogador.Cliente__r.FirstName;
        
        compraList = [
            SELECT Id, Name, Status__c, Fichas__c, Valor_Total__c,  
            Mesa__c, CreatedDate, CreatedBy.Name, FormaPagamento__c
            FROM CompraFicha__c
            WHERE SessaoCash__c =: sessaoJogador.Id
            ORDER BY CreatedDate DESC
        ];
        
        accClube = ClubeServico.getServico().obterClube(UserInfo.getUserId());
        
        atualizarValores();
    }
    
    private Boolean atualizarValorSessao(String sessaoId) {
        List<SessaoCash__c> sessaoJogadorList = [
            SELECT Id, Name, CreatedDate, FormaPagamento__c, Status__c,
            Cliente__c, Cliente__r.FirstName, Cliente__r.LastName, 
            CobrarTaxa__c,
            FichaDevolvida__c, TotalFichas__c, TotalFichasPendente__c, 
            ValorCompra__c, ValorTotalPago__c, ValorTotalPendente__c, ValorTotal__c
            
            FROM SessaoCash__c
            WHERE Id =: sessaoId AND Status__c = 'Aberta' AND SessaoCaixa__c =: sessaoCaixa.Id
        ];
        
        if(sessaoJogadorList.isEmpty()) {
            return false;
        }
        
        sessaoJogador = sessaoJogadorList.get(0);
        
        return true;
    }
    
    public PageReference atualizarValores() {
        this.btnAtivo = true;
        if(sessaoJogador.FichaDevolvida__c == null || sessaoJogador.FichaDevolvida__c < 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Fichas Devolvidas: É necessário informa um valor válido.'));
            return null;
        }
        
        sessaoJogador.ValorTotal__c = 
            sessaoJogador.FichaDevolvida__c - sessaoJogador.TotalFichasPendente__c;
        
        if(sessaoJogador.ValorTotal__c < 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'O CLIENTE ESTÁ COM O SALDO NEGATIVO: É necessário realizar a cobrança.'));
            
            if(sessaoJogador.CobrarTaxa__c) { 
                sessaoJogador.ValorTotal__c = 
                    ClubeServico.getServico().calcTaxa(sessaoJogador.FormaPagamento__c, sessaoJogador.ValorTotal__c);
            }
            
            
        } else if(sessaoJogador.ValorTotal__c > 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.CONFIRM, 'O CLIENTE ESTÁ COM O SALDO POSITIVO: É necessário realizar o pagamento.'));
            
            sessaoJogador.FormaPagamento__c  = 'Dinheiro';
            btnAtivo = false;
                
        } else {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.INFO, 'O CLIENTE ESTÁ COM O SALDO ZERADO:É necessário receber as fichas.'));   
            
        }
        
        return null;
    }
    
    public PageReference salvar() {
        
        if(sessaoJogador.FichaDevolvida__c == null || sessaoJogador.FichaDevolvida__c < 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Fichas Devolvidas: É necessário informa um valor válido.'));
            return null;
        }
        
        if(sessaoJogador.ValorTotal__c < 0 && String.isEmpty(sessaoJogador.FormaPagamento__c)) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Forma Pagamento: É necessário informa um valor.'));
            return null;
            
        } else if(sessaoJogador.ValorTotal__c > 0) {
            sessaoJogador.FormaPagamento__c  = 'Dinheiro';
        
        }
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            ClubeServico.getServico().desativarJogadorMesa(sessaoJogador.Cliente__c);
            
            sessaoJogador.DataFechamento__c = Datetime.now();
            sessaoJogador.UsuarioFechamento__c = UserInfo.getUserId();
            sessaoJogador.Status__c		 = 'Fechada';
            
            System.debug('Sessao: ' + sessaoJogador);
            
            UPDATE sessaoJogador;
            
            
            
        } catch(Exception ex) {
            Database.rollback(sp);
            System.debug('Ex: ' + ex);
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Ex: ' + ex.getMessage()));
            
            return null;
        }
        
        PageReference pageRef = new PageReference('/apex/Caixa?sfdc.tabName=01r61000000hoRV');
        return pageRef;
    }
    
    protected override String getUrl() {
        String chave = obterChaveContato(jogador);
        return '/apex/Caixa?sfdc.tabName=01r61000000hoRV&chave=' + chave;
    }
}