unpackaged/objects/ApexClass__c.object
<CustomObject>
    <fields>
        <fullName>Apex__c</fullName>
        <externalId>true</externalId>
        <label>Apex</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Apex Class</label>
    <nameField>
        <label>Nome de Apex Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ApexDeveloper__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>Apex Class</label>
        <referenceTo>ApexClass__c</referenceTo>
        <relationshipLabel>Apex Developers</relationshipLabel>
        <relationshipName>Apex_Developers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Apex_Developers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Apex Developer</label>
    <nameField>
        <label>Nome de ApexDeveloper</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Developers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ApexDeveloperLog__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Apex Class</label>
        <referenceTo>ApexClass__c</referenceTo>
        <relationshipLabel>Apex Developer Logs</relationshipLabel>
        <relationshipName>Apex_Developer_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApexDeveloper__c</fullName>
        <label>Apex Developer</label>
        <referenceTo>ApexDeveloper__c</referenceTo>
        <relationshipLabel>Apex Developer Logs</relationshipLabel>
        <relationshipName>Apex_Developer_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Apex Developer Log</label>
    <nameField>
        <label>Nome de Apex Developer Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Developer Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/ApexDeveloperService.cls
public class ApexDeveloperService {

	private static ApexDeveloperService apexDeveloperService;

	public static ApexDeveloperService getInstance() {
		if(apexDeveloperService == null) {
			apexDeveloperService = new ApexDeveloperService();
		}
		return apexDeveloperService;
	}

	public List<ApexDeveloper__c> find(List<ApexClass> apexClassList) {
		Set<String> apexSet = new Set<String>();
		for (ApexClass apexClass : apexClassList) {
			apexSet.add(apexClass.Id);
		}
		return [
				SELECT Id, Name, ApexClass__c, User__c, ApexClass__r.Apex__c
				FROM ApexDeveloper__c WHERE ApexClass__r.Apex__c IN: apexSet
		];
	}

	public List<ApexDeveloper__c> find(List<ApexClass__c> apexClassList) {
		return [
			SELECT Id, Name, ApexClass__c, User__c
			FROM ApexDeveloper__c WHERE ApexClass__c IN: apexClassList
		];
	}

	public User findUser(Id user) {
		return [
			SELECT Id, Name FROM User WHERE Id =: user
		];
	}

	public ApexDeveloper__c createApexDeveloper(ApexClass__c classy, ApexClass apexClass) {
		ApexDeveloper__c  apexDeveloper = new ApexDeveloper__c();
		apexDeveloper.ApexClass__c = classy.Id;
		apexDeveloper.Name = apexClass.CreatedBy.Name;
		apexDeveloper.User__c = apexClass.CreatedById;

		return apexDeveloper;
	}

	public ApexDeveloperLog__c createApexDeveloperLog(ApexDeveloper__c developer, ApexClass__c classy, ApexClass apexClass) {
		final ApexDeveloperLog__c log = new ApexDeveloperLog__c();
		log.Name = developer.Name;
		log.Message__c = 'Atualizou ';
		log.Date__c = apexClass.LastModifiedDate;
		log.ApexDeveloper__c = developer.Id;
		log.ApexClass__c = classy.Id;
		return log;
	}
}