unpackaged/objects/ApexClass__c.object
<CustomObject>
    <fields>
        <fullName>Apex__c</fullName>
        <externalId>true</externalId>
        <label>Apex</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Coverage__c</fullName>
        <label>Coverage</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>LinesCovegare__c</fullName>
        <label>Lines Covegare</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lines__c</fullName>
        <label>Lines</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Apex Classes</relationshipLabel>
        <relationshipName>Apex_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Class</label>
    <nameField>
        <label>Nome de Apex Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ApexClassMessage__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>Apex Class</label>
        <referenceTo>ApexClass__c</referenceTo>
        <relationshipLabel>Apex Classes messages</relationshipLabel>
        <relationshipName>Apex_Classes_messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Apex Class Message</label>
    <nameField>
        <label>Nome de Apex Class Message</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Classes messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Package__c.object
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Nome de Package</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ApexTestCoverageBatch.cls
global class ApexTestCoverageBatch extends AbstractService implements Database.Batchable<sObject>, Database.AllowsCallouts {

	private final String id;
	global ApexTestCoverageBatch(final String id) {
		this.id	 = id;
	}

	public Void execute(Database.BatchableContext jobId, List<Package__c> recordList) {
		final List<ApexClass__c> classList = ApexTestPackageService.getInstance().findApexClass(recordList.get(0));

		final Set<Id> classIdSet = new Set<Id>();
		for(ApexClass__c classy : classList) {
			System.debug(getClass() + '.onTestCompleted() res: ' + classy);
			classIdSet.add(classy.Apex__c);
		}

		final Map<String, ApexTestCoverageService.ApexCodeCoverageAggregate> codeCoverageMap =
				ApexTestCoverageService.getInstance().getCodeCoverage(classIdSet);

		final List<ApexClassMessage__c> newMessageList = new List<ApexClassMessage__c>();
		for(ApexClass__c apexClass : classList) {
			ApexTestCoverageService.ApexCodeCoverageAggregate coverage = codeCoverageMap.get(apexClass.Apex__c);
			if(coverage != null) {
				apexClass.LinesCovegare__c =  coverage.numLinesCovered;
				apexClass.Lines__c = coverage.numLinesCovered + coverage.numLinesUncovered;
				apexClass.Coverage__c = apexClass.LinesCovegare__c/apexClass.Lines__c * 100;

				if(apexClass.Coverage__c < 75) {
					final ApexClassMessage__c apexMessage = new ApexClassMessage__c();
					apexMessage.Name = 'Covegare Low';
					apexMessage.ApexClass__c = apexClass.Id;
					apexMessage.Outcome__c = 'warn';
					newMessageList.add(apexMessage);
				}
			}
		}

		Database.update(classList);
		Database.insert(newMessageList);
	}

	public Void finish(Database.BatchableContext jobId) {
	}

	public System.Iterable<sObject> start(Database.BatchableContext jobId) {
		return Database.getQueryLocator('SELECT Id FROM Package__c WHERE Id =\''
				+ id + '\'');
	}
}