unpackaged/objects/ApexClass__c.object
<CustomObject>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Apex Classes</relationshipLabel>
        <relationshipName>Apex_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Class</label>
    <nameField>
        <label>Nome de Apex Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ApexDeveloper__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>Apex Class</label>
        <referenceTo>ApexClass__c</referenceTo>
        <relationshipLabel>Apex Developers</relationshipLabel>
        <relationshipName>Apex_Developers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Developer</label>
    <nameField>
        <label>Nome de ApexDeveloper</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Developers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ApexDeveloperLog__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Apex Class</label>
        <referenceTo>ApexClass__c</referenceTo>
        <relationshipLabel>Apex Developer Logs</relationshipLabel>
        <relationshipName>Apex_Developer_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ApexDeveloper__c</fullName>
        <label>Apex Developer</label>
        <referenceTo>ApexDeveloper__c</referenceTo>
        <relationshipLabel>Apex Developer Logs</relationshipLabel>
        <relationshipName>Apex_Developer_Logs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Developer Log</label>
    <nameField>
        <label>Nome de Apex Developer Log</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Developer Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Package__c.object
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Nome de Package</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ApexDeveloperServiceTest.cls
/**
 * Created by andreleite on 05/10/17.
 */
@IsTest
private class ApexDeveloperServiceTest {

	@IsTest static void testGetInstance() {
		ApexDeveloperService apexDeveloperServi = ApexDeveloperService.getInstance();
		System.assertEquals(true, apexDeveloperServi != null);
	}

	@IsTest static void testFind() {
		final List<ApexClass> apexClassList = [
				SELECT Id, Name, CreatedDate, CreatedById, CreatedBy.Name,
				LastModifiedDate, LastModifiedById, LastModifiedBy.Name
				FROM ApexClass LIMIT 10];

		ApexDeveloperService apexDeveloperServi = ApexDeveloperService.getInstance();
		final List<ApexDeveloper__c> developerList = apexDeveloperServi.find(apexClassList);
		System.assertEquals(0, developerList.size());

		final Package__c packageApex = ApexClassService.getInstance().getPackageDefault();
		final ApexClass apexClass = apexClassList.get(0);
		final ApexClass__c classy = ApexClassService.getInstance().createClass(packageApex, apexClass);
		INSERT classy;

		System.assertEquals(apexClass.Name, classy.Name);

		final ApexDeveloper__c developer = ApexDeveloperService.getInstance().createApexDeveloper(classy, apexClass);
		INSERT developer;


		final List<ApexDeveloper__c> developerList2 = apexDeveloperServi.find(apexClassList);
		System.assertEquals(1, developerList2.size());

		final List<ApexDeveloper__c> developerList3 = apexDeveloperServi.find(new List<ApexClass__c> { classy });
		System.assertEquals(1, developerList2.size());

		System.assertEquals(developerList2.get(0).Id, developerList3.get(0).Id);

		final ApexDeveloperLog__c apexDeveloperLog = apexDeveloperServi.createApexDeveloperLog(developer, classy, apexClass);
		INSERT apexDeveloperLog;
		System.assertEquals(true, apexDeveloperLog != null);
	}

	@IsTest static void testFindUser() {
		ApexDeveloperService apexDeveloperServi = ApexDeveloperService.getInstance();
		final User user = apexDeveloperServi.findUser(UserInfo.getUserId());
		System.assertEquals(true, user != null);
	}
}