unpackaged/objects/ApexClass__c.object
<CustomObject>
    <fields>
        <fullName>Apex__c</fullName>
        <externalId>true</externalId>
        <label>Apex</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Package__c</fullName>
        <label>Package</label>
        <referenceTo>Package__c</referenceTo>
        <relationshipLabel>Apex Classes</relationshipLabel>
        <relationshipName>Apex_Classes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Apex Class</label>
    <nameField>
        <label>Nome de Apex Class</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Classes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/ApexClassMessage__c.object
<CustomObject>
    <fields>
        <fullName>ApexClass__c</fullName>
        <label>Apex Class</label>
        <referenceTo>ApexClass__c</referenceTo>
        <relationshipLabel>Apex Classes messages</relationshipLabel>
        <relationshipName>Apex_Classes_messages</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Message__c</fullName>
        <label>Message</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MethodName__c</fullName>
        <label>Method Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StackTrace__c</fullName>
        <label>Stack Trace</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Apex Class Message</label>
    <nameField>
        <label>Nome de Apex Class Message</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apex Classes messages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Package__c.object
<CustomObject>
    <label>Package</label>
    <nameField>
        <label>Nome de Package</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Packages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ApexTestRunPackageSchedulable.cls
public with sharing class ApexTestRunPackageSchedulable extends ApexTestRunSchedulable {

	private Package__c packag;

	public ApexTestRunPackageSchedulable(Package__c packag, Id testJobId) {
		super(packag.Name, testJobId);
		this.packag = packag;
	}

	public override void onTestCompleted(ApexTestResult[] results) {
		System.debug(getClass() + '.onTestCompleted() results: ' + results.size());

		//Database.executeBatch(new ApexTestCoverageBatch(packag.Id));

		final List<ApexClass__c> classList = ApexTestPackageService.getInstance().findApexClass(packag);

		final Map<String, ApexClass__c> apexClassMap = new Map<String, ApexClass__c>();
		Set<Id> deleteMessage = new Set<Id>();
		for(ApexClass__c cls : classList) {
			deleteMessage.add(cls.Id);
			apexClassMap.put(cls.Apex__c, cls);
		}

		final List<ApexClassMessage__c> messageList = [
			SELECT Id FROM ApexClassMessage__c WHERE ApexClass__c IN: deleteMessage
		];

		Database.delete(messageList);

		final List<ApexClassMessage__c> newMessageList = new List<ApexClassMessage__c>();
		for(ApexTestResult apexTest : results) {
			final ApexClass__c classsy = apexClassMap.get(apexTest.ApexClassId);

			if(isFail(apexTest)) {
				final ApexClassMessage__c apexMessage = createMessage(classsy, apexTest);
				newMessageList.add(apexMessage);
			}
		}

		Database.insert(newMessageList);
	}

	private ApexClassMessage__c createMessage(ApexClass__c classsy, ApexTestResult apexTest) {
		final ApexClassMessage__c apexMessage = new ApexClassMessage__c();
		apexMessage.Name = 'Test Erro';
		apexMessage.ApexClass__c = classsy.Id;
		apexMessage.Outcome__c = apexTest.Outcome;
		apexMessage.Message__c = apexTest.Message;
		apexMessage.MethodName__c = apexTest.MethodName;
		apexMessage.StackTrace__c = apexTest.StackTrace;
		return apexMessage;
	}

	public Package__c getPackag() {
		return packag;
	}
}