unpackaged/objects/CompraFicha__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Compras Fichas</relationshipLabel>
        <relationshipName>Compras_Fichas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Fichas__c</fullName>
        <label>Fichas</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FormaPagamento__c</fullName>
        <label>Forma Pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                    <default>true</default>
                    <label>Dinheiro</label>
                </value>
                <value>
                    <fullName>Cartão/Débito</fullName>
                </value>
                <value>
                    <fullName>Cartão/Crédito</fullName>
                </value>
                <value>
                    <fullName>Vale/Crédito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mesa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Compras Fichas</relationshipLabel>
        <relationshipName>Compras_Fichas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SessaoCash__c</fullName>
        <label>Sessao Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCash__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCash__c</referenceTo>
        <relationshipLabel>Compras Fichas</relationshipLabel>
        <relationshipName>Compras_Fichas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                </value>
                <value>
                    <fullName>Paga</fullName>
                    <default>true</default>
                    <label>Paga</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valor_Total__c</fullName>
        <label>Valor Total</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Compra Ficha</label>
    <nameField>
        <displayFormat>CF-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compras Fichas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Jogador</fullName>
        <active>true</active>
        <label>Jogador</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/JogadorMesa__c.object
<CustomObject>
    <fields>
        <fullName>DataAtivacao__c</fullName>
        <label>Data Ativação</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jogador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SessaoJogador__c</fullName>
        <label>Sessão Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCash__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCash__c</referenceTo>
        <relationshipLabel>Jogadores Mesas</relationshipLabel>
        <relationshipName>Jogadores_Mesas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
                <value>
                    <fullName>Em Espera</fullName>
                    <default>true</default>
                    <label>Em Espera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jogador Mesa</label>
    <nameField>
        <displayFormat>JM-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCash__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sess_es_Cash</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CobrarTaxa__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Cobrar Taxa de Pagamento</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FormaPagamento__c</fullName>
        <label>Forma de Pagamento</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dinheiro</fullName>
                </value>
                <value>
                    <fullName>Cartão/Débito</fullName>
                </value>
                <value>
                    <fullName>Cartão/Crédito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCaixa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sessao_Jogador</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Jogador</label>
    <nameField>
        <displayFormat>SJ-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Jogador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/JogadorFicha2Controller.cls
public with sharing class JogadorFicha2Controller extends AbstractCashController {
    
    public JogadorMesa__c jogadorMesa 	{ get;set; }
    public CompraFicha__c compraFicha	{ get;set; }
    private SessaoCash__c sessaoJogador { get;set; }
    
    public JogadorFicha2Controller() {}
    
    protected override void init() {
        
        if(sessaoCaixa == null) {
            return;
        }
        
        String jogMesaId = Apexpages.currentPage().getParameters().get('Id');
        if(!String.isEmpty(jogMesaId)) {
            List<JogadorMesa__c> jogadorMesaList = [
                SELECT Id, Mesa__c, SessaoJogador__c, DataAtivacao__c,
                Jogador__c, Jogador__r.FirstName, Jogador__r.LastName, Status__c
                FROM JogadorMesa__c
                WHERE Id =: jogMesaId AND Status__c = 'Ativo' AND Mesa__r.SessaoCaixa__c =: sessaoCaixa.Id
            ];
            
            if(!jogadorMesaList.isEmpty()) {
                jogadorMesa = jogadorMesaList.get(0);
                
                this.sessaoJogador = 
                    ClubeServico.getServico().criarSessao(new Contact(Id=jogadorMesa.Jogador__c));
            }
        }
        
        String paramJogadorId = Apexpages.currentPage().getParameters().get('jogId');
        if(!String.isEmpty(paramJogadorId)) {
            List<JogadorMesa__c> jogadorMesaList = [
                SELECT Id, Mesa__c, SessaoJogador__c, DataAtivacao__c,
                Jogador__c, Jogador__r.FirstName, Jogador__r.LastName, Status__c
                FROM JogadorMesa__c
                WHERE Status__c IN ('Ativo', 'Em Espera') AND Jogador__c =: paramJogadorId
                ORDER BY DataAtivacao__c DESC
            ];
            
            if(!jogadorMesaList.isEmpty()) {
                jogadorMesa = jogadorMesaList.get(0);
                
                this.sessaoJogador = 
                    ClubeServico.getServico().criarSessao(new Contact(Id=jogadorMesa.Jogador__c));
            
                if(jogadorMesa.Status__c == 'Em Espera') {
                    ApexPages.addMessage(new ApexPages.Message(
                        ApexPages.Severity.INFO, 'O jogador não está ativo'));
                }
            }
        }
        
        this.compraFicha = new CompraFicha__c();
        if(jogadorMesa != null) {
            this.compraFicha.Mesa__c = jogadorMesa.Mesa__c;
            this.compraFicha.Cliente__c 	= jogadorMesa.Jogador__c;
        }       
        this.compraFicha.Fichas__c 		= 0;
        this.compraFicha.Valor_Total__c = 0;
        
    }
    
    public PageReference atualizarValores() {
        
        if(compraFicha.Fichas__c <= 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Fichas: É necessário inserir um valor válido.'));
            return null;
        }
        
        System.debug('sessao jogador:' + sessaoJogador);
        if(sessaoJogador.CobrarTaxa__c) { 
            this.compraFicha.Valor_Total__c = 
                ClubeServico.getServico().calcTaxa(compraFicha.FormaPagamento__c, compraFicha.Fichas__c);
        }
        
        return null;
    }
    
    public PageReference finalizar() {
        if(compraFicha.Fichas__c <= 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Fichas: É necessário inserir o valor.'));
            return null;
        }
        
        //Desfazer o calculo, caso necessario a trigger fara o calc novamente.
        this.compraFicha.Valor_Total__c = compraFicha.Fichas__c;
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            System.debug('Compra Ficha: ' + compraFicha);
            INSERT compraFicha;
            
        } catch(Exception ex) {
            Database.rollback(sp);
            
            System.debug('Ex: ' + ex);
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Ex: ' + ex.getMessage()));
            
            return null;
        }
        
        PageReference pageRef = new PageReference('/apex/Jogador?sfdc.tabName=01r61000000ho8J');
        return pageRef;
    }
    
    protected override String getUrl() {
        return '/apex/Jogador?sfdc.tabName=01r61000000ho8J';
    }
    
}