unpackaged/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Jogador</fullName>
        <active>true</active>
        <label>Jogador</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/DealerSessao__c.object
<CustomObject>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessao Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Dealer</relationshipLabel>
        <relationshipName>Dealers_Sessao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Dealer</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Dealer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jogo__c</fullName>
        <label>Jogo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mix Texas/Omaha</fullName>
                </value>
                <value>
                    <fullName>Omaha</fullName>
                </value>
                <value>
                    <fullName>Texas Holdem</fullName>
                    <default>true</default>
                    <label>Texas Holdem</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo__c</fullName>
        <defaultValue>&quot;Nova Mesa&quot;</defaultValue>
        <description>Titulo pelo o qual a mesa é reconhecida por todos</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCash__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sess_es_Cash</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCaixa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sessao_Jogador</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Jogador</label>
    <nameField>
        <displayFormat>SJ-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Jogador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/SessaoCaixaController.cls
public with sharing class SessaoCaixaController extends AbstractCashController {

    public List<Mesa__c> mesaList 					{ get;set; }
    public List<SessaoCash__c> jogSessaoList 		{ get;set; }
    
    public String sessaoCaixaId { get;set; }
    public SessaoCaixaController(ApexPages.StandardController controller) {
        sessaoCaixaId = controller.getId();        
    }

    public PageReference atualizarSessao() {
        
        if(String.isEmpty(sessaoCaixaId)) {
            throw new UtilApex.UtilApexException('É necessario uma sesssão.'); 
        }
        
        ClubeServico.getServico().atualizarSessaoCaixa(sessaoCaixaId);
        
        ApexPages.addMessage(new ApexPages.Message(
            ApexPages.Severity.CONFIRM, 'Sessão Caixa atualizado com sucesso'));
        
        return null;
    }
    
    public PageReference fechamentoSessaoCaixa() {
        if(sessaoCaixaId == null) {
            throw new UtilApex.UtilApexException('É necessario uma sesssão.'); 
        }
        
        sessaoCaixa = [
            SELECT Id, Status__c, Name
            FROM SessaoCaixa__c
            WHERE Id =:sessaoCaixaId             
        ];
        
        if(sessaoCaixa == null) {
            throw new UtilApex.UtilApexException('É necessario uma sessão.'); 
            
        } else if(sessaoCaixa.Status__c != 'Aberta') {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'A sessão não está Aberta'));
            
            return null;
        }
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            verificarDependencias();
            
            if(!mesaList.isEmpty() || !jogSessaoList.isEmpty()) { 
                return null;
            }
            
            desativarSessaoDealer();
            
            sessaoCaixa.DataFechamento__c 	= Datetime.now();
            sessaoCaixa.Status__c 			= 'Fechada';
            
            UPDATE sessaoCaixa;
            
            atualizarSessao();
            
        } catch(Exception ex) {
            Database.rollback(sp);
            
            System.debug('Ex: ' + ex);
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Ex: ' + ex.getMessage()));
            
            return null;
        }
        
        PageReference page = new PageReference('/' + sessaoCaixaId);
        return page;
    }
    
    private void desativarSessaoDealer() {
        List<DealerSessao__c> dealerSessaoList = [
            SELECT Id
            FROM DealerSessao__c
            WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Ativo'
        ];
        
        for(DealerSessao__c dSe : dealerSessaoList) {
            dSe.Status__c = 'Desativo';
        }
        
        UPDATE dealerSessaoList;
    }
    
    private void verificarDependencias() {
        mesaList = [
            SELECT Id, Name, Titulo__c, Status__c, Jogo__c, CreatedDate
            FROM Mesa__c
            WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Aberta'
        ];
        
        jogSessaoList = [
            SELECT Id, Name, Cliente__c, Cliente__r.FirstName, Cliente__r.LastName, CreatedDate, Status__c
            FROM SessaoCash__c
            WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Aberta'
            ORDER BY CreatedDate DESC LIMIT 20
        ];
        
        if(!jogSessaoList.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Não é possível efetuar o fechamento, existem Sessões Jogador abertas.'));
        }
        
        if(!mesaList.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Não é possível efetuar o fechamento, existem Mesas abertas.'));
            
        }
    }
}