unpackaged/objects/DealerMesa__c.object
<CustomObject>
    <fields>
        <fullName>DataEntrada__c</fullName>
        <label>Data Entrada</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DataSaida__c</fullName>
        <label>Data Saída</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DealerSessao__c</fullName>
        <label>Dealer Sessão</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>DealerSessao__c.Status__c</field>
                <operation>equals</operation>
                <value>Ativo</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>DealerSessao__c</referenceTo>
        <relationshipLabel>Dealers Mesas</relationshipLabel>
        <relationshipName>Dealers_Mesas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Dealers Mesas</relationshipLabel>
        <relationshipName>Dealers_Mesas</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Mesa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Dealers Mesas</relationshipLabel>
        <relationshipName>Dealers_Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ValorCapile__c</fullName>
        <label>Valor Capilé</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Dealer Mesa</label>
    <nameField>
        <displayFormat>DM-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dealers Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/DealerSessao__c.object
<CustomObject>
    <fields>
        <fullName>DataEntrada__c</fullName>
        <label>Data Entrada</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DataSaida__c</fullName>
        <label>Data Saida</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Dealer</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Dealer</relationshipLabel>
        <relationshipName>Dealers_Sessao</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessao Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Dealer</relationshipLabel>
        <relationshipName>Dealers_Sessao</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Dealer</label>
    <nameField>
        <displayFormat>DS-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Dealer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/JogadorMesa__c.object
<CustomObject>
    <fields>
        <fullName>Jogador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
                <value>
                    <fullName>Em Espera</fullName>
                    <default>true</default>
                    <label>Em Espera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jogador Mesa</label>
    <nameField>
        <displayFormat>JM-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>Jogo__c</fullName>
        <label>Jogo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Mix Texas/Omaha</fullName>
                </value>
                <value>
                    <fullName>Omaha</fullName>
                </value>
                <value>
                    <fullName>Texas Holdem</fullName>
                    <default>true</default>
                    <label>Texas Holdem</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Titulo__c</fullName>
        <defaultValue>&quot;Nova Mesa&quot;</defaultValue>
        <description>Titulo pelo o qual a mesa é reconhecida por todos</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TotalFichasCapile__c</fullName>
        <label>Total Fichas Capilé (+)</label>
        <summarizedField>DealerMesa__c.ValorCapile__c</summarizedField>
        <summaryForeignKey>DealerMesa__c.Mesa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFichasCompradas__c</fullName>
        <label>Total Fichas Compradas (-)</label>
        <summarizedField>CompraFicha__c.Fichas__c</summarizedField>
        <summaryForeignKey>CompraFicha__c.Mesa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalFichasCapile__c</fullName>
        <label>Total Fichas Capilé (+)</label>
        <summarizedField>DealerSessao__c.ValorTotalCapile__c</summarizedField>
        <summaryForeignKey>DealerSessao__c.SessaoCaixa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorPendente__c</fullName>
        <label>Valor Pendente (-)</label>
        <summarizedField>SessaoCash__c.ValorTotalPendente__c</summarizedField>
        <summaryForeignKey>SessaoCash__c.SessaoCaixa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorTotalEspecie__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Total Espécie (+)</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ValorTotalSacado__c</fullName>
        <label>Valor Total Sacado (-)</label>
        <summarizedField>SessaoCash__c.ValorTotal__c</summarizedField>
        <summaryFilterItems>
            <field>SessaoCash__c.Status__c</field>
            <operation>equals</operation>
            <value>Fechada</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>SessaoCash__c.ValorTotal__c</field>
            <operation>greaterThan</operation>
            <value>0</value>
        </summaryFilterItems>
        <summaryForeignKey>SessaoCash__c.SessaoCaixa__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCash__c.object
<CustomObject>
    <fields>
        <fullName>Cliente__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Cliente</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sess_es_Cash</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCaixa__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Sessões Jogador</relationshipLabel>
        <relationshipName>Sessao_Jogador</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TotalFichasPendente__c</fullName>
        <label>Total Fichas Pendentes</label>
        <summarizedField>CompraFicha__c.Fichas__c</summarizedField>
        <summaryFilterItems>
            <field>CompraFicha__c.Status__c</field>
            <operation>equals</operation>
            <value>Aberta</value>
        </summaryFilterItems>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>TotalFichas__c</fullName>
        <label>Total Fichas</label>
        <summarizedField>CompraFicha__c.Fichas__c</summarizedField>
        <summaryForeignKey>CompraFicha__c.SessaoCash__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Sessão Jogador</label>
    <nameField>
        <displayFormat>SJ-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Jogador</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/CashHomeController.cls
public with sharing class CashHomeController extends AbstractCashController {
    
    public List<MesaView> mesaList 			 		{ get;set; }
    
    public List<SessaoJogadorView> sessaoJogadorList 	{ get;set; }
    public SessaoCaixa__c sessaoCaixaView 		{ get;set; }
    public String sessaoCaixaSelect 			{ get;set; }
    public List<SelectOption> sessaoCaixaOption { get;set; }
    public List<DealerSessao__c> dealerSessaoList { get;set; }
        
    public CashHomeController() {
        
        this.sessaoCaixaOption = new List<SelectOption>();
        if(sessaoCaixa != null) {
            sessaoCaixaOption.add(new SelectOption(sessaoCaixa.Id, formatCombo(sessaoCaixa)));
        }
        List<SessaoCaixa__c> sessaoCaixaList = [
            SELECT Id, Name, CreatedDate
            FROM SessaoCaixa__c
            WHERE CreatedDate = THIS_MONTH AND Status__c = 'Fechada'
            ORDER BY CreatedDate DESC
        ];
        
        for(SessaoCaixa__c sc : sessaoCaixaList ) {
            sessaoCaixaOption.add(new SelectOption(sc.Id, formatCombo(sc)));
        }
        if(!sessaoCaixaOption.isEmpty()) {
            this.sessaoCaixaSelect = (sessaoCaixa == null)  ? sessaoCaixaList.get(0).Id : sessaoCaixa.Id;
            loadData();
        }
        
    }
    
    private String formatCombo(SessaoCaixa__c sc) {
        Map<String, String> mapaSemana = UtilApex.mapaSemana;
        DateTime dt = DateTime.now();
        String semana = mapaSemana.get(sc.CreatedDate.format('EEEE'));
        String formattedDt = '[' + sc.Name + '] ' + sc.CreatedDate.format(' dd/MM/yyyy') + ' - '+ semana.toUpperCase() ;
        return formattedDt;
    }
    
    public PageReference atualizarCaixa() {
        if(sessaoCaixa != null) {
            ClubeServico.getServico().atualizarSessaoCaixa(sessaoCaixa.Id);       
        }
        return null;
    }
    
    protected override void init() { 
        //this.mesaSelect = new Mesa__c();
        this.mesaList 		= new List<MesaView>();
        this.sessaoJogadorList = new List<SessaoJogadorView>();
        this.dealerSessaoList = new List<DealerSessao__c>();
        
        //this.jogSessaoList 	= new List<SessaoCash__c>();
        //this.dealerMesaList 	= new List<DealerMesa__c>();
        
        if(sessaoCaixa == null) {
            return;
        }
        
        loadSessaoCaixa('' + sessaoCaixa.Id);
        
        /*this.sessaoCaixa = [
            SELECT Id, Name, CreatedDate,
            ValorTotalEspecie__c, ValorTotalSacado__c, ValorPendente__c
            FROM sessaoCaixa__c
            WHERE ID =: sessaoCaixa.Id
        ];*/
        
        /*this.mesaList = [
            SELECT Id, Name, Titulo__c, Jogo__c, TotalFichasCompradas__c
            FROM Mesa__c
            WHERE SessaoCaixa__c =: sessaoCaixa.Id AND Status__c = 'Aberta'
            ORDER BY CreatedDate DESC
        ];
        */
        //if(!this.mesaList.isEmpty()) {
        //    carregarJogadores(mesaList.get(0).Id);
        //}        
    }
    
    /*public PageReference carregarJogadores() {
        String mesaId = Apexpages.currentPage().getParameters().get('mesaId');
        
        if(!String.isEmpty(mesaId)) {
           carregarJogadores(mesaId);
        }
        
        return null;
    }
    
    private void carregarJogadores(String mesaId) {
        
        mesaSelect = [
            SELECT Id, Name
            FROM Mesa__c
            WHERE Id =: mesaId
        ].get(0);
      
        List<JogadorMesa__c> jogMesaList = [
            SELECT  Id, Jogador__c
            FROM JogadorMesa__c
            WHERE Mesa__c =: mesaId //AND Status__c IN('Ativo')
        ];
        
        Set<Id> jogId = new Set<Id>();
        for(JogadorMesa__c jM : jogMesaList) {
            jogId.add(jM.Jogador__c);
        }
        
        jogSessaoList = [
            SELECT Id, Name, Cliente__c, Cliente__r.FirstName, Cliente__r.LastName, CreatedDate, Status__c,
            TotalFichasPendente__c, TotalFichas__c
            FROM SessaoCash__c
            WHERE Cliente__c IN: jogId AND Status__c = 'Aberta' AND SessaoCaixa__c =: sessaoCaixaSelect
            ORDER BY TotalFichas__c DESC
        ];
        
        dealerMesaList = [
            SELECT Id, Name, Dealer__c, Dealer__r.LastName, Dealer__r.FirstName, DataEntrada__c, DataSaida__c, ValorCapile__c
            FROM DealerMesa__c
            WHERE Mesa__c =: mesaId
            ORDER BY DataSaida__c DESC
        ];
    }*/
    
    public void loadSessaoCaixa(String sesId) {
        this.sessaoCaixa = [
            SELECT Id, Name, CreatedDate,
            ValorTotalEspecie__c, ValorTotalSacado__c, ValorPendente__c
            FROM sessaoCaixa__c
            WHERE ID =: sesId
        ];
    }
    
    public void loadData() {
        
        if(sessaoCaixaSelect == null) {
            return;
        }
        
        loadSessaoCaixa(sessaoCaixaSelect);
        
        SessaoCaixa__c sc = [
            SELECT Name
            FROM SessaoCaixa__c
            WHERE Id =: sessaoCaixaSelect
        ];   
        
        this.sessaoCaixaList = [
            SELECT Id, Name, CreatedDate, CreatedBy.Name, Status__c
            FROM SessaoCaixa__c
            WHERE ID =: sessaoCaixaSelect
        ];
        
        List<Mesa__c> mList = [
            SELECT Id, Name, Titulo__c, Jogo__c,
            TotalFichasCompradas__c, TotalFichasCapile__c, ValorRake__c, ValorTotalVenda__c
            FROM Mesa__c
            WHERE SessaoCaixa__c =: sc.Id
            ORDER BY CreatedDate DESC
        ];
        this.mesaList = new List<MesaView>();
        for(Mesa__c mesa : mList) {
            mesaList.add(new MesaView(mesa));
        }
        
        this.dealerSessaoList = [
            SELECT Id, Name, Dealer__c, Dealer__r.LastName, Dealer__r.FirstName,
            ValorTotalCapile__c, Status__c, DataEntrada__c, DataSaida__c
            FROM DealerSessao__c
            WHERE SessaoCaixa__c =: sc.Id
            ORDER BY DataSaida__c DESC
        ];
        
        List<SessaoCash__c> sJogadorList = [
            SELECT Id, Name, Cliente__c, Cliente__r.FirstName, Cliente__r.LastName, 
            DataInicioSessao__c, DataFechamento__c, Status__c, FormaPagamento__c,
            TotalFichasPendente__c, TotalFichas__c, FichaDevolvida__c
            FROM SessaoCash__c
            WHERE SessaoCaixa__c =: sc.Id
            ORDER BY TotalFichas__c DESC
        ];
        
        this.sessaoJogadorList = new List<SessaoJogadorView>();
        for(SessaoCash__c s : sJogadorList) {
            SessaoJogadorView sjView = new SessaoJogadorView(s);
            this.sessaoJogadorList.add(sjView);
        }
    }
    
    public class MesaView {
        public Mesa__c mesa { get;set; }
        public Decimal taxa { get;set; }
        
        public MesaView(Mesa__c mesa) {
            this.mesa = mesa;
            this.taxa = mesa.ValorTotalVenda__c - mesa.TotalFichasCompradas__c;
        }
    }
    
    public class SessaoJogadorView {
        public SessaoCash__c sCash { get;set; }
        public Integer totalHoras  		{ get;set; }
        public Decimal valor			{ get;set; }
        
        public SessaoJogadorView(SessaoCash__c sessaoCash) {
            this.sCash = sessaoCash;
            System.debug('sessaoCash:' + sessaoCash);
            if(sessaoCash.DataInicioSessao__c != null && sessaoCash.DataFechamento__c != null) {
                this.totalHoras = 
                    sessaoCash.DataInicioSessao__c.Date().daysBetween(sessaoCash.DataFechamento__c.Date());
            }
            
            if(sessaoCash.FichaDevolvida__c != null && sessaoCash.TotalFichas__c != null) {
                this.valor = sessaoCash.FichaDevolvida__c - sessaoCash.TotalFichas__c;
            }
        }
    }
}