unpackaged/objects/JogadorMesa__c.object
<CustomObject>
    <fields>
        <fullName>DataAtivacao__c</fullName>
        <label>Data Ativação</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Jogador__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Jogador</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Mesa__c</fullName>
        <label>Mesa</label>
        <referenceTo>Mesa__c</referenceTo>
        <relationshipLabel>Jogadores Mesa</relationshipLabel>
        <relationshipName>Jogadores_Mesa</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SessaoJogador__c</fullName>
        <label>Sessão Jogador</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>SessaoCash__c.Status__c</field>
                <operation>equals</operation>
                <value>Aberta</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>SessaoCash__c</referenceTo>
        <relationshipLabel>Jogadores Mesas</relationshipLabel>
        <relationshipName>Jogadores_Mesas</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ativo</fullName>
                </value>
                <value>
                    <fullName>Desativo</fullName>
                </value>
                <value>
                    <fullName>Em Espera</fullName>
                    <default>true</default>
                    <label>Em Espera</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Jogador Mesa</label>
    <nameField>
        <displayFormat>JM-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/Mesa__c.object
<CustomObject>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SessaoCaixa__c</fullName>
        <label>Sessão Caixa</label>
        <referenceTo>SessaoCaixa__c</referenceTo>
        <relationshipLabel>Mesas</relationshipLabel>
        <relationshipName>Mesas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ValorRake__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Rake (+)</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Mesa</label>
    <nameField>
        <displayFormat>M-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mesas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/SessaoCaixa__c.object
<CustomObject>
    <fields>
        <fullName>DataFechamento__c</fullName>
        <label>Data Fechamento</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Aberta</fullName>
                    <default>true</default>
                    <label>Aberta</label>
                </value>
                <value>
                    <fullName>Fechada</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Sessão Caixa</label>
    <nameField>
        <displayFormat>SC-{00000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sessões Caixa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/MesaController.cls
public with sharing class MesaController extends AbstractCashController {

    public String mesaId 	{ get;set; }
    
    public Mesa__c mesa 	{ get;set; }
    
    public Boolean efetuarFechamento { get;set; }
    
    public List<JogadorMesa__c> jMesaList { get; set; }
    
    public MesaController(ApexPages.StandardController controller) {
        mesaId = controller.getId();
        efetuarFechamento = false;
    }
    
    public PageReference fechamentoMesa() {
        
        if(String.isEmpty(mesaId)) {
            throw new UtilApex.UtilApexException('É necessario uma mesa.'); 
        }
        
        mesa = [
            SELECT Id, Status__c, ValorRake__c, Name, SessaoCaixa__c
            FROM Mesa__c
            WHERE Id =: mesaId
        ];
        
        if(mesa == null) {
            throw new UtilApex.UtilApexException('É necessario uma mesa.'); 
            
        } else if(mesa.Status__c != 'Aberta') {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'A Mesa não está Aberta'));
            
            return null;
        }
        
        jMesaList = [
            SELECT Id, Jogador__c, SessaoJogador__c, CreatedDate, Status__c, DataAtivacao__c, Mesa__c
            FROM JogadorMesa__c
            WHERE Status__c = 'Ativo'  AND Mesa__c =: mesa.Id
            ORDER BY CreatedDate DESC
        ];
        
        if(!jMesaList.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Não é possível efetuar o fechamento, existe(m) jogador(es) ativo(s) na(s) mesa(s).'));
            
            return null;
        }
        
        efetuarFechamento = true;
        
        ApexPages.addMessage(new ApexPages.Message(
            ApexPages.Severity.WARNING, 'Por favor informe o valor do Rake e confirme a operação.'));
        
        return null;
    }
    
    public PageReference efetuarFechamento() {
        
        if(mesa.ValorRake__c == null || mesa.ValorRake__c <= 0) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Por favor informe: valor do Rake.'));
            
            return null;
        }
        
        mesa.Status__c = 'Fechada';
        mesa.DataFechamento__c = Datetime.now();
        
        UPDATE mesa;
        //ClubeServico.getServico().atualizarMesa(mesa);
        
        PageReference page = new PageReference('/' + mesa.Id);
        return page;
    }
}