unpackaged/objects/Torneio__c.object
<CustomObject>
    <fields>
        <fullName>DataFinal__c</fullName>
        <description>Data da finalização do torneio</description>
        <inlineHelpText>Data de finalização do torneio</inlineHelpText>
        <label>Data Final</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DataInicio__c</fullName>
        <description>Data de início do torneio</description>
        <inlineHelpText>Data de início do torneio</inlineHelpText>
        <label>Data Início</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Titulo__c</fullName>
        <description>Titulo do torneio</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Torneio</label>
    <nameField>
        <displayFormat>T{00000}</displayFormat>
        <label>Nome de Torneio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torneios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TorneioEvento__c.object
<CustomObject>
    <fields>
        <fullName>Torneio__c</fullName>
        <label>Torneio</label>
        <referenceTo>Torneio__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Torneio Evento</label>
    <nameField>
        <label>Nome de Torneio Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torneio Eventos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/TorneioServicoTest.cls
/**
 * Created by andreleite on 01/10/17.
 */
@IsTest
private class TorneioServicoTest {

	@IsTest
	static void testGetServico() {
		Torneio__c torneio = new Torneio__c();
		torneio.Titulo__c = 'Titulo';
		torneio.DataInicio__c = Datetime.now();
		torneio.DataFinal__c = Datetime.now();
		INSERT torneio;

		TorneioServico torneioServ = TorneioServico.getServico();
		List<TorneioEvento__c> eventos = torneioServ.obterEventos(torneio.Id);

		System.assertEquals(false, eventos.isEmpty(), 'Nenhum eventos encontrado');
	}

	@IsTest
	static void testObterEventos() {

	}
}