unpackaged/objects/Torneio__c.object
<CustomObject>
    <fields>
        <fullName>Descricao__c</fullName>
        <label>Descrição</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Titulo__c</fullName>
        <description>Titulo do torneio</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ValorAddOn__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Add-On</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ValorBuyIn__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Buy-In</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ValorRebuy__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Rebuy</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ValorTaxa__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Valor Taxa</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Torneio</label>
    <nameField>
        <displayFormat>T{00000}</displayFormat>
        <label>Nome de Torneio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torneios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TorneioCompra__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pago</fullName>
                </value>
                <value>
                    <fullName>Pendente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Tipo__c</fullName>
        <label>Tipo</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Buy In</fullName>
                </value>
                <value>
                    <fullName>Rebuy</fullName>
                </value>
                <value>
                    <fullName>Add On</fullName>
                </value>
                <value>
                    <fullName>Taxa BuyIn</fullName>
                </value>
                <value>
                    <fullName>Taxa Rebuy</fullName>
                </value>
                <value>
                    <fullName>Time Chip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TorneioEvento__c</fullName>
        <label>Torneio Evento</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>TorneioEvento__c.Status__c</field>
                <operation>equals</operation>
                <value>Não Iniciado, Em Andamento, Parado</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>TorneioEvento__c</referenceTo>
        <relationshipLabel>Torneio Compras</relationshipLabel>
        <relationshipName>TorneioCompras</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TorneioInscricao__c</fullName>
        <label>Torneio Inscrição</label>
        <referenceTo>TorneioInscricao__c</referenceTo>
        <relationshipLabel>Torneio Compras</relationshipLabel>
        <relationshipName>Torneio_Compras</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Torneio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Torneio</label>
        <referenceTo>Torneio__c</referenceTo>
        <relationshipLabel>Torneio Compras</relationshipLabel>
        <relationshipName>Torneio_Compras</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Torneio Compra</label>
    <nameField>
        <displayFormat>TC{000000}</displayFormat>
        <label>Código</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torneio Compras</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/TorneioEstrutura__c.object
<CustomObject>
    <fields>
        <fullName>Descricao__c</fullName>
        <label>Descrição</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>NivelAddOn__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nível Add On</label>
        <referenceTo>TorneioNivel__c</referenceTo>
        <relationshipLabel>NivelAddOn</relationshipLabel>
        <relationshipName>Torneios_Estrururas</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NivelRebuy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nível Rebuy</label>
        <referenceTo>TorneioNivel__c</referenceTo>
        <relationshipLabel>Torneios Estrururas (Nível Rebuy)</relationshipLabel>
        <relationshipName>NivelRebuy</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StackAddOn__c</fullName>
        <label>Stack Add On</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StackBuyIn__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Stack Buy In</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Torneio Estrutura</label>
    <nameField>
        <label>Nome da Estrutura</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torneios Estrururas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TorneioEvento__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estrutura__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estrutura</label>
        <referenceTo>TorneioEstrutura__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nível</label>
        <referenceTo>TorneioNivel__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Não Iniciado</fullName>
                    <default>true</default>
                    <label>Não Iniciado</label>
                </value>
                <value>
                    <fullName>Em Andamento</fullName>
                </value>
                <value>
                    <fullName>Finalizado</fullName>
                </value>
                <value>
                    <fullName>Parado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Torneio__c</fullName>
        <label>Torneio</label>
        <referenceTo>Torneio__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Torneio Evento</label>
    <nameField>
        <label>Nome de Torneio Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torneio Eventos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/TorneioInscricao__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pré Inscrito</fullName>
                </value>
                <value>
                    <fullName>Inscrito</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Torneio__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Torneio</label>
        <referenceTo>Torneio__c</referenceTo>
        <relationshipLabel>Torneio Inscrições</relationshipLabel>
        <relationshipName>Torneio_Inscri_es</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ValorAddOn__c</fullName>
        <label>Valor Add On</label>
        <summarizedField>TorneioCompra__c.Valor__c</summarizedField>
        <summaryFilterItems>
            <field>TorneioCompra__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Add On</value>
        </summaryFilterItems>
        <summaryForeignKey>TorneioCompra__c.TorneioInscricao__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorBuyIn__c</fullName>
        <label>Valor Buy In</label>
        <summarizedField>TorneioCompra__c.Valor__c</summarizedField>
        <summaryFilterItems>
            <field>TorneioCompra__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Buy In</value>
        </summaryFilterItems>
        <summaryForeignKey>TorneioCompra__c.TorneioInscricao__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>ValorRebuy__c</fullName>
        <label>Valor Rebuy</label>
        <summarizedField>TorneioCompra__c.Valor__c</summarizedField>
        <summaryFilterItems>
            <field>TorneioCompra__c.Tipo__c</field>
            <operation>equals</operation>
            <value>Rebuy</value>
        </summaryFilterItems>
        <summaryForeignKey>TorneioCompra__c.TorneioInscricao__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Torneio Inscrição</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Código Inscrição</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torneio Inscrições</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/objects/TorneioNivel__c.object
<CustomObject>
    <fields>
        <fullName>Nivel__c</fullName>
        <label>Nível</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                    <default>true</default>
                    <label>1</label>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TorneioEstrutura__c</fullName>
        <label>Torneio Estrutura</label>
        <referenceTo>TorneioEstrutura__c</referenceTo>
        <relationshipLabel>Torneios Níveis</relationshipLabel>
        <relationshipName>Torneios_Niveis</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Torneio Nível</label>
    <nameField>
        <label>Nome de TorneioNivel</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torneios Níveis</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/TorneioInscricaoController.cls
public with sharing class TorneioInscricaoController {
    
    public Account accClube 			{ get;set; }
    
    public String textoChave 			{ get;set; }
    public List<Contact> jogadorList 	{ get;set; }

    public String torSelect				{ get;set; }
    public String evtSelect				{ get;set; }
    
    public Torneio__c			torneio	  { get;set; }
    public TorneioEvento__c 	evento	  { get;set; }
    public TorneioEstrutura__c 	estrutura { get;set; }
    
    public Contact 				  jogador 	  { get;set; }
    public TorneioInscricao__c	  inscricao	  { get;set; }
    public TorneioCompra__c 	  tCompra     { get;set; }
    public List<TorneioCompra__c> comprasList { get;set; }
    
    public List<TorneioInscricao__c> inscricaoList { get;set; }
    public Boolean isByIn {
        get {
            
            if(this.estrutura.StackBuyIn__c == null) {
                return false;
            }
            
            for(TorneioCompra__c c : comprasList) {
                if(c.Tipo__c == 'Buy In') {
                    return false;
                }
            }
            return true;
        }
    }

    public Boolean isInscricao {
        get {
            if(evtSelect == null || this.estrutura.StackBuyIn__c == null ||
               inscricao.Id != null) {
                   return false;
               }
            
            if(this.evento.Nivel__r.Nivel__c == null || 
               this.evento.Nivel__r.Nivel__c > this.estrutura.NivelRebuy__r.Nivel__c) {
                   return false;
               } 
            
            return true;
        }
    }
    
    public Boolean isRebuy {
        get {
            if(torneio.ValorRebuy__c == 0) {
                return false;
            }
            
            if(this.evtSelect == null || 
               this.estrutura.StackBuyIn__c == null || 
               this.inscricao.Id == null) {
                   return false;
               }
            
            if(this.evento.Status__c != 'Em Andamento') {
                return false;
            }
            
            if(this.evento.Nivel__r.Nivel__c == null || 
               this.evento.Nivel__r.Nivel__c > this.estrutura.NivelRebuy__r.Nivel__c) {
                   return false;
               } 
            
            for(TorneioCompra__c c : comprasList) {
                if(c.Tipo__c == 'Rebuy' && c.Id == null) {
                    return false;
                }
            }
            
            return true;
        }
    }
    
    public Boolean isAddOn {
        get {
            if(torneio.ValorAddOn__c == 0) {
                return false;
            }
            
            if(this.evtSelect == null || 
               this.estrutura.StackAddOn__c == null || 
               this.inscricao.Id == null) {
                   return false;
               }
            
            if(this.evento.Status__c != 'Em Andamento') {
                return false;
            }
            
            if(this.evento.Nivel__r.Nivel__c == null || 
               this.evento.Nivel__c != this.estrutura.NivelAddon__c) {
                   return false;
               } 
            
            for(TorneioCompra__c c : comprasList) {
                if(c.Tipo__c == 'Add On') {
                    return false;
                }
            }
            
            return true;
        }
    }
    
    public List<SelectOption> eventoSelect { get;set;}
    public List<SelectOption> torneioSelect {
        get {
            List<SelectOption> listSelect = new List<SelectOption>();
            
            Datetime dat = Datetime.newInstance(
                Datetime.now().date().year(), 
                Datetime.now().date().month(), 
                Datetime.now().date().day(), 0, 0, 0);
            
            List<TorneioEvento__c> torneioList = [
                SELECT Torneio__c, Torneio__r.Name, Torneio__r.Titulo__c
                FROM TorneioEvento__c
                
                WHERE Data__c >: dat 
                AND Status__c != 'Finalizado' 
                AND Nivel__c != null
                AND Estrutura__c != null
                ORDER BY Torneio__r.Titulo__c DESC
            ];
            
            Set<String> titulosSet = new Set<String>();
            for(TorneioEvento__c tv : torneioList) {
                if(this.torSelect == null) {//nenhum torneio selecionado?
                    this.torSelect = tv.Torneio__c;
                    selectTorneio();
                }
                
                String titulo = tv.Torneio__r.Titulo__c + ' ' + tv.Torneio__r.Name;
                if(!titulosSet.contains(titulo)) {
                    titulosSet.add(titulo);
                    listSelect.add(new SelectOption(tv.Torneio__c, titulo));
                }
                
            }
           
            return listSelect;
        }
    }
    
    public TorneioInscricaoController() {
        this.accClube = 
            ClubeServico.getServico().obterClube(UserInfo.getUserId());
        this.evento = new TorneioEvento__c();
        this.eventoSelect = new List<SelectOption>();
        this.comprasList = new List<TorneioCompra__c>();
        this.inscricaoList = new List<TorneioInscricao__c>();
    }
    
    public void selectJogador() {
        String jogId = 
            Apexpages.currentPage().getParameters().get('jogId');
        if(String.isEmpty(jogId)) {
            return;
        } 
        
        this.jogador = [
            SELECT Id, FirstName, LastName
            FROM Contact
            WHERE Id =: jogId
        ];
        
        selectEvento();
        
        this.textoChave = null;
    }
    
    public void selectTorneio() {
        if(String.isEmpty(torSelect)) {
            return;
        }
        limparForm();//LIMPAR DADOS SELECIONADOS
        
        this.torneio = [
            SELECT Titulo__c, ValorBuyIn__c, ValorRebuy__c, 
            ValorAddOn__c, ValorTaxa__c, Descricao__c
            FROM Torneio__c
            WHERE Id =:torSelect
        ];
        
        Datetime dat = Datetime.newInstance(
            Datetime.now().date().year(), 
            Datetime.now().date().month(), 
            Datetime.now().date().day(), 0, 0, 0);
        
        List<TorneioEvento__c> torneioList = [
            SELECT Name, Data__c
            FROM TorneioEvento__c
            WHERE Torneio__c =: torSelect 
            AND Data__c >: dat 
            AND Status__c != 'Finalizado' 
            AND Nivel__c != null
            AND Estrutura__c != null
            ORDER BY Data__c DESC
        ];
        
        this.eventoSelect.clear();
        for(TorneioEvento__c ev : torneioList) {
            this.eventoSelect.add(new SelectOption(ev.Id, ev.Name));
        }
    }
    
    public void selectEvento() {
        limparForm();
        if(String.isEmpty(evtSelect)) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.INFO, 'Selecione um evento para a inscrição do torneio'));
            return;
        }
        
        this.evento = [
            SELECT Name, Data__c, Estrutura__c,
            Nivel__r.Name,  Nivel__r.Nivel__c, Nivel__r.DuracaoBlinds__c, 
            Status__c
            
            FROM TorneioEvento__c
            WHERE Id =: evtSelect
        ];
        
        List<TorneioEstrutura__c> estList = [
            SELECT StackBuyIn__c, StackAddOn__c,
            NivelRebuy__r.Nivel__c, NivelAddon__c
            FROM TorneioEstrutura__c
            WHERE Id=: evento.Estrutura__c 
        ];
        
        if(estList.isEmpty()) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.WARNING, 
                'O Evento selecionado não possui estrutura configurada.'));
            return;
            
        } else {
            this.estrutura = estList.get(0);
            this.inscricaoList = [
                SELECT Name, DataInscricao__c,
                Jogador__c, Jogador__r.FirstName, Jogador__r.LastName, 
                Status__c, StatusPlayer__c
                FROM TorneioInscricao__c
                WHERE Torneio_Evento__c =: evtSelect 
                AND Status__c = 'Inscrito' AND StatusPlayer__c != 'Caiu'
            ];
            
            if(jogador == null) {
                return; 
            }
            
            List<TorneioInscricao__c> insList = [
                SELECT Name, DataInscricao__c,
                Torneio__r.Titulo__c, Torneio_Evento__r.Name,
                Jogador__c, Jogador__r.FirstName, Jogador__r.LastName, 
                Status__c, StatusPlayer__c
                FROM TorneioInscricao__c
                WHERE Torneio_Evento__c =: evtSelect AND Jogador__c =: jogador.Id 
                AND Status__c = 'Inscrito' AND StatusPlayer__c != 'Caiu'
                ORDER BY CreatedDate DESC
                LIMIT 1
            ];
            
            if(!insList.isEmpty()) {
                this.inscricao = insList.get(0);
                this.jogador = new Contact();
                this.jogador.Id = this.inscricao.Jogador__c;
                this.jogador.FirstName = this.inscricao.Jogador__r.FirstName;
                this.jogador.LastName = this.inscricao.Jogador__r.LastName;
                
                this.comprasList = [
                    SELECT Tipo__c, Valor__c, ValorTotal__c, Fichas__c, Status__c,
                    FormaPagamento__c, CreatedById
                    FROM TorneioCompra__c
                    WHERE TorneioInscricao__c =: this.inscricao.Id
                ];
                 
            } else {
                addByIn();    
            }
        }
    }
    
    private void limparForm() {
        this.evento = new TorneioEvento__c();
        this.tCompra = new TorneioCompra__c();
        this.inscricao = new TorneioInscricao__c();
        this.inscricao.Jogador__c = (this.jogador != null) ? this.jogador.Id : null;     
        this.comprasList.clear();
        this.inscricaoList.clear();
        ApexPages.getMessages().clear();
    }
    
    public void buscar() {
        
        if(String.isEmpty(this.textoChave)) {
            return;
        }
        
        this.textoChave = this.textoChave.trim();
        
        jogadorList = Database.query(
            'SELECT Id, FirstName, LastName, MobilePhone, Email ' 	+ 
            'FROM Contact ' + 
            'WHERE RecordTypeId = \'' + UtilApex.getRecordTypeId('Contact', 'Jogador') + '\'' 				+
            (String.isNotBlank( textoChave ) ? ' AND (FirstName LIKE \'%' + this.textoChave + 
             '%\' OR LastName LIKE \'%' 		+ this.textoChave + 
             '%\' OR Email LIKE \'%' 			+ this.textoChave +
             '%\' OR MobilePhone LIKE \'%' 		+ this.textoChave +
             '%\')' : '') +
            ' ORDER BY LastName ASC LIMIT 100'
        );
    }
    
    public void addAddOn() {
        if(!isAddOn) {
            return;
        }
        
        TorneioCompra__c tc = new TorneioCompra__c();
        tc.Tipo__c 			= 'Add On';
        tc.Valor__c 		= torneio.ValorAddOn__c;
        tc.Fichas__c 		= this.estrutura.StackAddOn__c;
        
        this.comprasList.add(tc);
        
        atualizarCompra();
    }
    
    public void addRebuy() {
        if(!isRebuy) {
            return;
        }
        TorneioCompra__c tc = new TorneioCompra__c();
        tc.Tipo__c 			= 'Rebuy';
        tc.Valor__c 		= torneio.ValorRebuy__c;
        tc.Fichas__c 		= this.estrutura.StackBuyIn__c;
        
        TorneioCompra__c tx = new TorneioCompra__c();
        tx.Tipo__c 			= 'Taxa Rebuy';
        tx.Valor__c 		= torneio.ValorTaxa__c;
        tx.Fichas__c 		= 0;
        
        this.comprasList.add(tx);
        this.comprasList.add(tc);
        
        atualizarCompra();
    }
    
    public void addByIn() {
        TorneioCompra__c tc = new TorneioCompra__c();
        tc.Tipo__c 			= 'Buy In';
        tc.Valor__c 		= torneio.ValorBuyIn__c;
        tc.Fichas__c 		= this.estrutura.StackBuyIn__c;
        
        TorneioCompra__c tx = new TorneioCompra__c();
        tx.Tipo__c 			= 'Taxa BuyIn';
        tx.Valor__c 		= torneio.ValorTaxa__c;
        tx.Fichas__c 		= 0;
        
        comprasList.add(tx);
        comprasList.add(tc);
        
        atualizarCompra();
    }
    
    private void atualizarCompra() {
        Decimal total = 0;
        for(TorneioCompra__c t : comprasList) {
            if(t.Id == null) {
                total += t.Valor__c;
            }
        }
        
        this.tCompra = new TorneioCompra__c();
        this.tCompra.Status__c 		= 'Pago';
        this.tCompra.ValorTotal__c = total;
    }
    
    public void formaPagamento() {
        if(String.isEmpty(this.tCompra.FormaPagamento__c)) {
            return;
        }
        
        Decimal total = 0;
        for(TorneioCompra__c t : comprasList) {
            if(t.Id == null) {
                t.FormaPagamento__c = this.tCompra.FormaPagamento__c;
                Decimal valor = ClubeServico.getServico().calcTaxa(
                    this.tCompra.FormaPagamento__c, t.Valor__c);
                t.ValorTotal__c = valor;
                total += valor;
            }
        }
        this.tCompra.ValorTotal__c = total;
    }
    
    public void fazerInscricao() {
        
        if(String.isEmpty(tCompra.FormaPagamento__c)) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.WARNING, 
                'Forma de Pagamento: É necessário informar'));
            return;
            
        }
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            
            this.inscricao.Jogador__c = this.jogador.Id;
            this.inscricao.DataInscricao__c = Datetime.now();
            this.inscricao.Status__c = 'Inscrito';
            this.inscricao.Torneio__c = torneio.Id;
            this.inscricao.Torneio_Evento__c = evento.Id;
            
            INSERT this.inscricao;
            
            for(TorneioCompra__c c : comprasList) {
                c.FormaPagamento__c = this.tCompra.FormaPagamento__c;
                c.Torneio__c		= this.torneio.Id;
                c.TorneioEvento__c 	= this.evento.Id;
                c.TorneioInscricao__c = this.inscricao.Id;
                c.Status__c			= this.tCompra.Status__c;
            }
            
            UPSERT this.comprasList;
            
            selectEvento();
            
        } catch(Exception ex) {
            Database.rollback(sp);
            System.debug('Ex: ' + ex);
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Ex: ' + ex.getMessage()));
        }
    }
    
    public void salvar() {
        if(String.isEmpty(tCompra.FormaPagamento__c)) {
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.WARNING, 
                'Forma de Pagamento: É necessário informar'));
            return;
            
        }
        
        Savepoint sp = Database.setSavepoint();
        
        try {
            List<TorneioCompra__c> saveList = new List<TorneioCompra__c>();
            for(TorneioCompra__c c : comprasList) {
                if(c.Id == null) {
                    c.Torneio__c		= this.torneio.Id;
                    c.TorneioEvento__c 	= this.evento.Id;
                    c.TorneioInscricao__c = this.inscricao.Id;
                    c.Status__c			= this.tCompra.Status__c;
                    saveList.add(c);     
                }
            }
            
            INSERT saveList;
            
            selectEvento();
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.CONFIRM, 
                'Alterações salvas com sucesso'));
            
        } catch(Exception ex) {
            Database.rollback(sp);
            System.debug('Ex: ' + ex);
            
            ApexPages.addMessage(new ApexPages.Message(
                ApexPages.Severity.ERROR, 'Ex: ' + ex.getMessage()));
        }
    }
}