unpackaged/objects/Torneio__c.object
<CustomObject>
    <fields>
        <fullName>Titulo__c</fullName>
        <description>Titulo do torneio</description>
        <label>Titulo</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <label>Torneio</label>
    <nameField>
        <displayFormat>T{00000}</displayFormat>
        <label>Nome de Torneio</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Torneios</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/objects/TorneioEvento__c.object
<CustomObject>
    <fields>
        <fullName>Data__c</fullName>
        <label>Data</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Estrutura__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Estrutura</label>
        <referenceTo>TorneioEstrutura__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Nivel__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Nível</label>
        <referenceTo>TorneioNivel__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Não Iniciado</fullName>
                    <default>true</default>
                    <label>Não Iniciado</label>
                </value>
                <value>
                    <fullName>Em Andamento</fullName>
                </value>
                <value>
                    <fullName>Finalizado</fullName>
                </value>
                <value>
                    <fullName>Parado</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Torneio__c</fullName>
        <label>Torneio</label>
        <referenceTo>Torneio__c</referenceTo>
        <relationshipLabel>Torneio Eventos</relationshipLabel>
        <relationshipName>Torneio_Eventos</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Torneio Evento</label>
    <nameField>
        <label>Nome de Torneio Evento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Torneio Eventos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/classes/TorneioServico.cls
public with sharing class TorneioServico {

    public static TorneioServico torneioServico = null;
    public static TorneioServico getServico() {
        if(torneioServico == null) {
            torneioServico = new TorneioServico();
        }
        return torneioServico;
    }
    
    public List<TorneioEvento__c> obterEventos(String torneioId) {
        if(!String.isEmpty(torneioId)) {
            List<TorneioEvento__c> torneioList = [
                SELECT Name, Data__c
                FROM TorneioEvento__c
                WHERE Torneio__c =: torneioId 
                AND Data__c >: Datetime.now() 
                AND Status__c != 'Finalizado' 
                AND Nivel__c != null
                AND Estrutura__c != null
                ORDER BY Data__c DESC
            ];     
        }
       
        return [
            SELECT Torneio__c, Torneio__r.Name, Torneio__r.Titulo__c
            FROM TorneioEvento__c
            WHERE Data__c >: Datetime.now() AND Status__c != 'Finalizado' AND Nivel__c != null
            ORDER BY Torneio__r.Titulo__c DESC
        ];
    }
}